CREATE TABLE public.profiles (
id uuid NOT NULL,
email text,
role text,
emergency_contact text,
bio text,
facebook_url text,
instagram_url text,
linkedin_url text,
airbnb_url text,
community_support_badge text,
support_preferences text[],
support_story text,
profile_photo_url text,
display_lat numeric,
display_lng numeric,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
first_name text,
last_name text,
phone_number text,
emergency_contact_name text,
emergency_contact_number text,
emergency_contact_email text,
other_social_url text,
other_support_description text,
street_address text,
state text,
zip_code text,
city text,
neighborhood text,
CONSTRAINT profiles_pkey PRIMARY KEY (id),
CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.account_deletion_requests (
id uuid NOT NULL DEFAULT gen_random_uuid(),
user_id uuid NOT NULL,
requested_at timestamp with time zone NOT NULL DEFAULT now(),
scheduled_deletion_date timestamp with time zone NOT NULL,
status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'cancelled'::text, 'processing'::text, 'completed'::text])),
reason text,
admin_notes text,
processed_at timestamp with time zone,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
CONSTRAINT account_deletion_requests_pkey PRIMARY KEY (id),
CONSTRAINT account_deletion_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.dogs (
id uuid NOT NULL DEFAULT gen_random_uuid(),
owner_id uuid,
name text NOT NULL,
breed text,
birthday date,
age_years integer DEFAULT 0,
age_months integer DEFAULT 0,
size text CHECK (size = ANY (ARRAY['0-10'::text, '11-25'::text, '26-40'::text, '41-70'::text, '71-90'::text, '91-110'::text])),
photo_url text,
gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text])),
neutered boolean DEFAULT false,
temperament text[],
energy_level text CHECK (energy_level = ANY (ARRAY['low'::text, 'moderate'::text, 'high'::text])),
dog_friendly boolean DEFAULT true,
cat_friendly boolean DEFAULT false,
kid_friendly boolean DEFAULT false,
leash_trained boolean DEFAULT false,
crate_trained boolean DEFAULT false,
house_trained boolean DEFAULT false,
fully_vaccinated boolean DEFAULT false,
activities text[],
description text,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
CONSTRAINT dogs_pkey PRIMARY KEY (id),
CONSTRAINT dogs_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.availability (
id uuid NOT NULL DEFAULT gen_random_uuid(),
owner_id uuid,
dog_id uuid,
post_type text NOT NULL CHECK (post_type = ANY (ARRAY['dog_available'::text, 'petpal_available'::text])),
title text NOT NULL,
description text,
start_date date,
end_date date,
start_time time without time zone,
end_time time without time zone,
duration_minutes integer,
is_recurring boolean DEFAULT false,
recurring_days text[],
flexibility_level text CHECK (flexibility_level = ANY (ARRAY['strict'::text, 'moderate'::text, 'flexible'::text])),
availability_notes text,
special_instructions text,
is_urgent boolean DEFAULT false,
urgency_notes text,
display_lat numeric,
display_lng numeric,
city_label text,
use_profile_location boolean DEFAULT true,
custom_location_address text,
custom_location_neighborhood text,
custom_location_city text,
custom_location_state text,
custom_location_zip_code text,
custom_location_lat numeric,
custom_location_lng numeric,
can_drop_off boolean DEFAULT false,
can_pick_up boolean DEFAULT false,
preferred_meeting_location text,
status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'completed'::text, 'cancelled'::text])),
community_support_enabled boolean DEFAULT false,
support_preferences text[],
flexible_scheduling_needed boolean DEFAULT false,
support_story text,
enabled_days jsonb DEFAULT '{}'::jsonb,
day_schedules jsonb DEFAULT '{}'::jsonb,
need_extra_help boolean DEFAULT false,
help_reason_elderly boolean DEFAULT false,
help_reason_sick boolean DEFAULT false,
help_reason_low_income boolean DEFAULT false,
help_reason_disability boolean DEFAULT false,
help_reason_single_parent boolean DEFAULT false,
help_context text,
open_to_helping_others boolean DEFAULT false,
can_help_elderly boolean DEFAULT false,
can_help_sick boolean DEFAULT false,
can_help_low_income boolean DEFAULT false,
can_help_disability boolean DEFAULT false,
can_help_single_parent boolean DEFAULT false,
helping_others_context text,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
can_help_everyone boolean DEFAULT false,
help_reason_other boolean DEFAULT false,
help_reason_other_text text,
can_pick_up_drop_off boolean DEFAULT false,
dog_ids uuid[] DEFAULT '{}'::uuid[],
CONSTRAINT availability_pkey PRIMARY KEY (id),
CONSTRAINT availability_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
CONSTRAINT availability_dog_id_fkey FOREIGN KEY (dog_id) REFERENCES public.dogs(id)
);
CREATE TABLE public.conversations (
id uuid NOT NULL DEFAULT gen_random_uuid(),
participant1_id uuid NOT NULL,
participant2_id uuid NOT NULL,
availability_id uuid,
last_message_at timestamp with time zone DEFAULT now(),
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
availability_post_id uuid,
CONSTRAINT conversations_pkey PRIMARY KEY (id),
CONSTRAINT conversations_participant1_id_fkey FOREIGN KEY (participant1_id) REFERENCES public.profiles(id),
CONSTRAINT conversations_participant2_id_fkey FOREIGN KEY (participant2_id) REFERENCES public.profiles(id),
CONSTRAINT conversations_availability_id_fkey FOREIGN KEY (availability_id) REFERENCES public.availability(id),
CONSTRAINT conversations_availability_post_id_fkey FOREIGN KEY (availability_post_id) REFERENCES public.availability(id)
);
CREATE TABLE public.email_catalog (
id text NOT NULL,
description text NOT NULL,
enabled boolean DEFAULT true,
created_at timestamp with time zone DEFAULT now(),
CONSTRAINT email_catalog_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_events (
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
user_id uuid NOT NULL,
email_type text NOT NULL,
status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'sent'::text, 'failed'::text, 'skipped'::text])),
external_message_id text,
error text,
to_email text NOT NULL,
subject text,
payload jsonb DEFAULT '{}'::jsonb,
created_at timestamp with time zone DEFAULT now(),
CONSTRAINT email_events_pkey PRIMARY KEY (id),
CONSTRAINT email_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
CONSTRAINT email_events_email_type_fkey FOREIGN KEY (email_type) REFERENCES public.email_catalog(id)
);
CREATE TABLE public.meetings (
id uuid NOT NULL DEFAULT gen_random_uuid(),
requester_id uuid NOT NULL,
recipient_id uuid NOT NULL,
availability_id uuid,
conversation_id uuid,
title text NOT NULL,
description text,
meeting_place text,
start_datetime timestamp with time zone NOT NULL,
end_datetime timestamp with time zone NOT NULL,
status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'cancelled'::text, 'completed'::text])),
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
reminder_sent boolean DEFAULT false,
requester_dog_id uuid,
recipient_dog_id uuid,
CONSTRAINT meetings_pkey PRIMARY KEY (id),
CONSTRAINT meetings_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.profiles(id),
CONSTRAINT meetings_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
CONSTRAINT meetings_availability_id_fkey FOREIGN KEY (availability_id) REFERENCES public.availability(id),
CONSTRAINT meetings_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
CONSTRAINT meetings_requester_dog_id_fkey FOREIGN KEY (requester_dog_id) REFERENCES public.dogs(id),
CONSTRAINT meetings_recipient_dog_id_fkey FOREIGN KEY (recipient_dog_id) REFERENCES public.dogs(id)
);
CREATE TABLE public.messages (
id uuid NOT NULL DEFAULT gen_random_uuid(),
sender_id uuid NOT NULL,
recipient_id uuid NOT NULL,
availability_id uuid,
subject text,
content text NOT NULL,
is_read boolean DEFAULT false,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
conversation_id uuid,
CONSTRAINT messages_pkey PRIMARY KEY (id),
CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
CONSTRAINT messages_availability_id_fkey FOREIGN KEY (availability_id) REFERENCES public.availability(id),
CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.profile_views (
id uuid NOT NULL DEFAULT gen_random_uuid(),
viewer_id uuid,
viewed_user_id uuid NOT NULL,
created_at timestamp with time zone DEFAULT now(),
CONSTRAINT profile_views_pkey PRIMARY KEY (id),
CONSTRAINT profile_views_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES public.profiles(id),
CONSTRAINT profile_views_viewed_user_id_fkey FOREIGN KEY (viewed_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reviews (
id uuid NOT NULL DEFAULT gen_random_uuid(),
reviewer_id uuid NOT NULL,
reviewee_id uuid NOT NULL,
conversation_id uuid,
availability_id uuid,
rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
review_text text,
reviewer_role text NOT NULL CHECK (reviewer_role = ANY (ARRAY['owner'::text, 'walker'::text])),
reviewed_role text NOT NULL CHECK (reviewed_role = ANY (ARRAY['owner'::text, 'walker'::text])),
meeting_date date,
meeting_location text,
status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'hidden'::text, 'deleted'::text])),
is_pending boolean DEFAULT false,
review_trigger_date timestamp with time zone,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
meeting_id uuid,
comment text NOT NULL,
CONSTRAINT reviews_pkey PRIMARY KEY (id),
CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.profiles(id),
CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES public.profiles(id),
CONSTRAINT reviews_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
CONSTRAINT reviews_availability_id_fkey FOREIGN KEY (availability_id) REFERENCES public.availability(id),
CONSTRAINT reviews_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id)
);
CREATE TABLE public.reviews_pending (
id uuid NOT NULL DEFAULT gen_random_uuid(),
user_id uuid NOT NULL,
conversation_id uuid NOT NULL,
other_participant_id uuid NOT NULL,
availability_id uuid,
role text NOT NULL CHECK (role = ANY (ARRAY['owner'::text, 'walker'::text])),
other_role text NOT NULL CHECK (other_role = ANY (ARRAY['owner'::text, 'walker'::text])),
days_since_last_message integer NOT NULL,
is_notified boolean DEFAULT false,
notification_sent_at timestamp with time zone,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
CONSTRAINT reviews_pending_pkey PRIMARY KEY (id),
CONSTRAINT reviews_pending_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
CONSTRAINT reviews_pending_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
CONSTRAINT reviews_pending_other_participant_id_fkey FOREIGN KEY (other_participant_id) REFERENCES public.profiles(id),
CONSTRAINT reviews_pending_availability_id_fkey FOREIGN KEY (availability_id) REFERENCES public.availability(id)
);
CREATE TABLE public.scheduled_emails (
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
user_id uuid NOT NULL,
email_type text NOT NULL,
run_after timestamp with time zone NOT NULL,
payload jsonb DEFAULT '{}'::jsonb,
picked_at timestamp with time zone,
created_at timestamp with time zone DEFAULT now(),
CONSTRAINT scheduled_emails_pkey PRIMARY KEY (id),
CONSTRAINT scheduled_emails_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
CONSTRAINT scheduled_emails_email_type_fkey FOREIGN KEY (email_type) REFERENCES public.email_catalog(id)
);
CREATE TABLE public.user_activity (
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
user_id uuid NOT NULL,
event text NOT NULL,
metadata jsonb DEFAULT '{}'::jsonb,
at timestamp with time zone DEFAULT now(),
CONSTRAINT user_activity_pkey PRIMARY KEY (id),
CONSTRAINT user_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_settings (
user_id uuid NOT NULL,
email_notifications boolean NOT NULL DEFAULT true,
follow_up_email_sent boolean NOT NULL DEFAULT false,
follow_up_email_sent_at timestamp with time zone,
created_at timestamp with time zone DEFAULT now(),
updated_at timestamp with time zone DEFAULT now(),
CONSTRAINT user_settings_pkey PRIMARY KEY (user_id),
CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);